import { ToolsService } from './toolsService.js';

let CategoryService = {
	getRandomCategory: function(){
		let largeCatList = [
			"Carbonated Beverages",
			"Milk",
			"Fresh Bread & Rolls",
			"Salty Snacks",
			"Beer/Ale/Alcoholic Cider"/*,
			"Natural Cheese",
			"Wine",
			"Fz Dinners/Entrees",
			"Cold Cereal",
			"Cigarettes",
			"Yogurt",
			"Rfg Juices/Drinks",
			"Ice Cream/Sherbet",
			"Bottled Water",
			"Soup",
			"Crackers",
			"Cookies",
			"Bottled Juices",
			"Coffee","Luncheon Meats",
			"Breakfast Meats",
			"Rfg Fresh Eggs",
			"Toilet Tissue",
			"Dog Food",
			"Total Chocolate Candy",
			"Fz Pizza","Rfg Salad/Coleslaw",
			"Fz Novelties",
			"Laundry Detergent",
			"Vegetables",
			"Fz Seafood",
			"Spirits/Liquor",
			"Snack Bars/Granola Bars",
			"Baby Formula/Electrolytes","Processed Cheese","Shortening & Oil","Fz/Rfg Poultry","Cat Food","Spices/Seasonings","Dinner Sausage","Paper Towels","Fz Plain Vegetables","Creams/Creamers","Processed Fz/Rfg Poultry","Frankfurters","Pastry/Doughnuts","Sports Drinks","Fz Breakfast Food","Pasta","Spaghetti/Italian Sauce","Pickles/Relish/Olives","Mexican Foods","Canned/Bottled Fruit","Snack Nuts/Seeds/Corn Nuts","Seafood – Ss","Food & Trash Bags","Salad Dressings – Ss","Rfg Side Dishes","Rice","Total Non-Chocolate Candy","Butter","Dry Packaged Dinners","Fz Meat","Margarine/Spreads/Butter Blen","Dough/Biscuit Dough – Rfg","Tea/Coffee Ready-To-Drink","Mayonnaise","Baking Needs","Sugar","Ss Dinners","Cups & Plates","Baking Mixes","Tomato Products","Vitamins","Fz Potatoes/Onions","Rfg Meat","Soap","Bakery Snacks","Diapers","Household Cleaner","Pies & Cakes","Mexican Sauce","Ss Meat & Rfg Ham","Fz Appetizers/Snack Rolls","Dish Detergent","Cream Cheese/Cr Chs Spread","Peanut Butter","Jellies/Jams/Honey","Internal Analgesics","Gravy/Sauce Mixes","Cottage Cheese","Energy Drinks","Aseptic Juices","Gum","Rfg Entrees","Hot Cereal","Lunches – Rfg","Sour Cream","Mustard & Ketchup","All Other Sauces","Baby Food","Cold/Allergy/Sinus Tablets","Toothpaste","Tea – Bags/Loose","Weight Con/Nutrition Liq/Pwd","Fz Bread/Fz Dough","Pet Supplies","Gastrointestinal – Tablets","Facial Tissue","Sanitary Napkins/Tampons","Flour/Meal","Cat/Dog Litter","Dried Fruit","Shampoo","Popcorn/Popcorn Oil","Syrup/Molasses","Deodorant","Drink Mixes","Baking Nuts","Batteries","Air Fresheners","Gelatin/Pudding Prd And Mixes","Foils & Wraps","Desserts -Rfg","Baked Beans/Canned Bread","Fz Desserts/Topping","Skin Care","Blades","English Muffins","Spreads – Rfg","Rfg Whipped Toppings","Canned Juices – Ss","Rfg Dips","Fz Pies","Cleaning Tools/Mops/Brooms","Toaster Pastries/Tarts","Dry Fruit Snacks","Toothbrush/Dental Accesories","Barbeque Sauce","Rfg Teas/Coffee","Charcoal","Sugar Substitutes","Fz Fruit","Asian Food","Paper Napkins","Fabric Softener Liquid","Hair Conditioner","Seafood – Rfg","Moist Towelettes","Juices – Frozen","Dip/Dip Mixes – Ss\Candles","Dry Beans/Vegetables","Mouthwash","Misc. Snacks","Instant Potatoes","Coffee Creamer","Kitchen Storage","Vinegar","Eye/Contact Lens Care Product","Evaporated/Condensed Milk","Milk Flavoring/Cocoa Mixes","Frosting","Fz Prepared Vegetables","Hand & Body Lotion","Hair Coloring","Bleach","Breadcrumbs/Batters","Other Rfg Products","Non-Fruit Drinks","Light Bulbs","Fz Pasta","Laundry Care","Salad Toppings","Smokeless Tobacco","Fz Pot Pies","Dessert Toppings","Foil Pans","Pest Control","Tea – Instant Tea Mixes","Baked Goods – Rfg","Salad Dressing – Rfg","Misc Health Remedies","Adult Incontinence","Rfg Tortlla/Eggrll/Wontn Wrap","Dried Meat Snacks","Sponges & Scouring Pads","Pizza – Rfg","Steak/Worcestershire Sauce","Rug/Upholstery/Fabric Treatmt","Pancake Mixes","Pasta – Rfg","Fz Side Dishes","Stuffing Mixes","First Aid Treatment","First Aid Accessories","Premixed Cocktails/Coolers","Fabric Softener Sheets","Gastrointestinal – Liquid","Hair Styling Gel/Mousse","Cold/Allergy/Sinus Liquids","Cosmetics – Eye","Suntan Products","Firelog/Firestarter/Firewood","Pickles/Relish – Rfg","Disposable Tableware","Rice/Popcorn Cakes","Croutons","Hair Spray/Spritz","Household Cleaner Cloths","Cocktail Mixes","Cough Drops","Cosmetics – Facial","Baby Accessories","Nasal Products","Baby Needs","Hair Accessories","Marshmallows","Foot Care Products","Office Products","Coffee Filters","Cigars","Cosmetics – Nail","Cheesecakes","Feminine Needs","Specialty Nut Butter","Cough Syrup","Shaving Cream","Fz Corn On The Cob","Denture Products","Cotton Balls/Swabs","All Other Breakfast Food","Pizza Products","Socks","Shaving Lotion/Mens Fragrance","Ice Cream Cones/Mixes","Razors","Childrens Art Supplies","Cosmetics – Lip","Lighters","Furniture Polish","Water Softeners/Treatment","Other Frozen Foods","Writing Instruments","Automobile Fluids/Antifreeze","Contraceptives","External Analgesic Rubs","Gloves","Charcoal Lighter Fluids","Floor Cleaners/Wax Removers","Anti-Smoking Products","Sleeping Remedies","Water Filters/Devices","All Other Tobacco Products","Motor Oil","Family Planning","Pantyhose/Nylons","Fragrances – Women’s","Baking Cups/Paper"*/];
		
		return ToolsService.getRandomArrayValue(largeCatList);
	},
	getRandomAdjective: function(){
		let largeAdjectiveList = [
			"cultural",
			"ten",
			"plucky",
			"uptight",
			"hollow",
			"well-off",
			"quarrelsome",
			"spurious",
			"spotty",
			"omniscient",
			"ajar",
			"mean",
			"obeisant",
			"fumbling",
			"observant",
			"filthy",
			"acrid",
			"squalid",
			"understood",
			"moldy",
			"entertaining",
			"alcoholic"/*,
			"latter","pastoral","noxious","mature","pure","mere","popular","dirty","subdued","greasy","seemly","silent","lying","diligent","wealthy","guilty","inner","steady","elastic","near","mad","fair","beautiful","deafening","possible","different","good","amused","fertile","bored","worried","vast","rainy","scared","onerous","eager","deadpan","irate","roomy","nice","absent","fresh","animated","functional","kind","highfalutin","flashy","changeable","unusual","nonchalant","thinkable","thick","loud","narrow","wry","permissible","shaky","relevant","embarrassed","swanky","equable","frightened","nauseating","macho","noiseless","tranquil","violet","plucky","ten","bent","tangible","milky","encouraging","volatile","half","empty","male","recent","far-flung","scary","quaint","married","wiry","familiar","jealous","efficient","nappy","elderly","tart","detailed","whimsical","waggish","squealing","alcoholic","mushy","warlike","incandescent","crowded","optimal","courageous","telling","lewd","homeless","unhappy","daily","present","different","half","eastern","changeable","foreign","laughable","thoughtful","big","spicy","dusty","sable","ancient","tested","conscious","utter","calculating","highfalutin","needy","low","torpid","parched","dull","electric","annoying","thinkable","waggish","puzzling","complete","encouraging","feigned","knotty","basic","nippy","innocent","berserk","direful","royal","languid","thundering","hurried","delicious","elegant","nifty","coordinated","spotty","vengeful","juicy","hot","cluttered","psychedelic","enchanted","absorbed","ossified","wise","immediate","handsome","hollow","modern","round","watery","several","obvious","erratic","hurt","statuesque","lame","faithful","alleged","worried","equable","stereotyped","public"*/];
		return ToolsService.getRandomArrayValue(largeAdjectiveList);	
	},
	getRandomFoodName: function(){
		let largeFoodList = [
	    "Cheese ",
	    "Pasta ",
	    "Noodles ",
	    "Puree ",
	    "Pimento ",
	    "Milk ",
	    "Turkey ",
	    "Pepper ",
	    "Sprouts ",
	    "Water ",
	    "Pork ",
	    "Veal ",
	    "Sugar ",
	    "Longos ",
	    "Icecream ",
	    "Flour ",
	    "Coke ",
	    "Basil ",
	    "Lemonade ",
	    "Syrup ",
	    "Broccoli ",
	    "Lettuce ",
	    "Nut ",
	    "Bread ",
	    "Beef ",
	    "Sauce ",
	    "Container ",
	    "Mayonnaise ",
	    "Clams ",
	    "Muffin ",
	    "Vinegar ",
	    "Chocolate ",
	    "Onions ",
	    "Beer ",
	    "Wine "/*,
	    "Muffin Mix ",
	    "Compound ",
	    "Appetizer ",
	    "Chinese Foods ",
	    "Soda Water ",
	    "Crush ",
	    "Clam ",
	    "Yeast Dry ",
	    "Eel ",
	    "Banana ",
	    "Mints ",
	    "Sea Bass ",
	    "Ice Cream ",
	    "Mushroom ",
	    "Artichokes ",
	    "Chicken ",
	    "Foil ",
	    "Juice ",
	    "Irish Cream ",
	    "Crab ",
	    "Seedlings ",
	    "Beans ",
	    "Bandage ",
	    "Soup ",
	    "Melon ",
	    "Skirt ",
	    "Squid U5 ",
	    "Chives ",
	    "Edible Flower ",
	    "Broom ",
	    "Pike ",
	    "Spinach ",
	    "Oil ",
	    "Flower ",
	    "Cake ",
	    "Coriander ",
	    "Aspic ",
	    "Snails ",
	    "Oxtail ",
	    "Pastry ",
	    "Venison ",
	    "Pate ",
	    "Chips ",
	    "Quail ",
	    "Cinnamon ",
	    "Grapefruit ",
	    "Sole ",
	    "Ocean Spray ",
	    "Lamb ",
	    "Zucchini ",
	    "Garbage Bags ",
	    "Liqueur ",
	    "Brandy ",
	    "Island Oasis ",
	    "Rice Wine ",
	    "Dc ",
	    "Rabbit ",
	    "Monkfish ",
	    "Mousse ",
	    "Bouq All Italian ",
	    "Tea ",
	    "Lobster ",
	    "Tortillas ",
	    "Lamb Rack ",
	    "Beets ",
	    "Lid ",
	    "Rum ",
	    "Coffee Beans ",
	    "Bagel ",
	    "Flavouring ",
	    "Plums ",
	    "Nantucket ",
	    "Tomatoes ",
	    "Muffins ",
	    "Sobe ",
	    "Miso ",
	    "Vermouth ",
	    "Arizona ",
	    "Yogurt ",
	    "Pie Box ",
	    "Pail ",
	    "Shrimp ",
	    "Tomato ",
	    "Carbonated Water ",
	    "Olives ",
	    "Langers ",
	    "Oven Mitts ",
	    "Mix ",
	    "Yeast ",
	    "Artichoke ",
	    "Coffee ",
	    "Extract ",
	    "Lemon Balm ",
	    "Napkin ",
	    "Cookie ",
	    "Apple ",
	    "Scallop ",
	    "Towel ",
	    "Mushrooms ",
	    "Onion ",
	    "Goat ",
	    "Dill ",
	    "Ecolab ",
	    "Ginger ",
	    "Asparagus ",
	    "Cookie Dough ",
	    "Placemat ",
	    "Apricots ",
	    "Corn ",
	    "Pop ",
	    "Mussels ",
	    "Piping Jelly ",
	    "True ",
	    "Sambuca ",
	    "Chocolate Bar ",
	    "Turnip ",
	    "Rice ",
	    "Versatainer Nc ",
	    "Pork Loin Bine ",
	    "Red Snapper ",
	    "Crackers ",
	    "Potatoes ",
	    "Fib N9 ",
	    "Cookies ",
	    "Eggs ",
	    "Chip ",
	    "Peas ",
	    "Chick Peas ",
	    "Tart ",
	    "Ice Cream Bar ",
	    "Cloves ",
	    "Cherries ",
	    "Vegetable ",
	    "Spoon ",
	    "Sprite, Diet ",
	    "Bacardi Breezer ",
	    "Cape Capensis ",
	    "Sprite ",
	    "Nougat ",
	    "Anchovy Paste ",
	    "Danishes ",
	    "Pie Shell ",
	    "Lid Tray ",
	    "The Pop Shoppe ",
	    "Scallops ",
	    "Corn Kernels ",
	    "Nestea ",
	    "Sausage ",
	    "Curry Paste ",
	    "Numi ",
	    "Loaf Pan ",
	    "Chestnuts ",
	    "Sparkling Wine ",
	    "Cranberries ",
	    "Snapple ",
	    "Evaporated Milk ",
	    "Pesto ",
	    "Pear ",
	    "Buffalo ",
	    "Sun ",
	    "Fish ",
	    "Shopper Bag ",
	    "Chickhen ",
	    "Energy Drink ",
	    "Bar ",
	    "Lentils ",
	    "Hummus ",
	    "Bread Base ",
	    "Mustard ",
	    "Muffin Carrot ",
	    "Muffin Batt ",
	    "Pie Filling ",
	    "Dip ",
	    "Triple Sec ",
	    "Cup ",
	    "Chutney Sauce ",
	    "Sour Puss ",
	    "Squid ",
	    "Rosemary ",
	    "French Pastry ",
	    "Fond ",
	    "Steam Pan ",
	    "Salmon Atl.whole 8 ",
	    "Trueblue ",
	    "Sloe Gin ",
	    "Dr. Pepper ",
	    "Raisin ",
	    "Hagen Daza ",
	    "Barley ",
	    "Glass ",
	    "Tuna ",
	    "Cabbage ",
	    "Bowl 12 Oz ",
	    "Skewers ",
	    "Saskatoon Berries ",
	    "Stock ",
	    "Food Colouring ",
	    "Jello ",
	    "Arctic Char ",
	    "Doilies ",
	    "Salmon ",
	    "Squash ",
	    "Capon ",
	    "Lighter ",
	    "Oregano ",
	    "Parsley ",
	    "Shark ",
	    "Halibut ",
	    "Prunes ",
	    "Grouper ",
	    "Spice ",
	    "Garlic ",
	    "Sherbet ",
	    "Cognac ",
	    "Knife Plastic ",
	    "Ham "*/
		];	
		
		return ToolsService.getRandomArrayValue(largeFoodList);
	}
}

export { CategoryService };